### ISSUE TITLE
Exposing the number of cores in PerformPopulationPCA

### ISSUE THREAD

**Issue by fabio-cunial** [broadinstitute/palantir-workflows#148]
It might be useful to expose the number of cores in the input of task `LDPruning`, since the task can take hours and plink2 seems to automatically use all cores available (it does not need the number of cores to be specified in input). The same holds for `ScoreVcf`, `ExtractIDsPlink`, and also `PerformPCA`, since one can do `flashpca --numthreads` (flashpca takes just 40 mins with 64 cores on the Thousand Genomes hg38 joint VCF).

**Comment by kockan** [comment]
Resolved.
