### ISSUE TITLE
Replace ${basename} with ~{basename} in PerformPCA

### ISSUE THREAD

**Issue by fabio-cunial** [broadinstitute/palantir-workflows#149]
On [this line](https://github.com/broadinstitute/palantir-workflows/blob/319b27d155035a8e05dd42794a6456094fc633f0/ImputationPipeline/PCATasks.wdl#L18). The task crashes in Terra since `${basename}` gets replaced with the empty string.

**Comment by kockan** [comment]
Fixed.
