### ISSUE TITLE
plink2 --set-all-var-ids in PCATasks.ArrayVcfToPlinkDataset

### ISSUE THREAD

**Issue by fabio-cunial** [broadinstitute/palantir-workflows#151]
Task `PCATasks.ArrayVcfToPlinkDataset` fails with `Error: No variants remaining after main filters.` even though I made sure that `vcf` and `pruning_sites` use the same lex format for their variant IDs. E.g. these are the first few lines of my `vcf`:

```
chr1    10126   chr1:10126:C:T  T       C       .       .       RAF=0.000853867;AF=5.00076e-05;INFO=1   GT:DS:GP        0|0:0:1,0,0
chr1    10134   chr1:10134:A:ACCCTAACCCTAAC     ACCCTAACCCTAAC  A       .       .       RAF=0.000243962;AF=0;INFO=1     GT:DS:GP        0|0:0:1,0,0
chr1    10138   chr1:10138:T:TA TA      T       .       .       RAF=0.000365943;AF=0;INFO=1     GT:DS:GP        0|0:0:1,0,0
chr1    10140   chr1:10140:A:ACCCTAAC   ACCCTAAC        A       .       .       RAF=0.00170773;AF=0.00050962;INFO=1     GT:DS:GP        0|0:0.001:0.999,0.001,0
chr1    10144   chr1:10144:T:TA TA      T       .       .       RAF=0.000609905;AF=1.70318e-05;INFO=1   GT:DS:GP        0|0:0:1,0,0
chr1    10144   chr1:10144:T:TAACCCC    TAACCCC T       .       .       RAF=0.00170773;AF=3.68063e-05;INFO=1    GT:DS:GP        0|0:0:1,0,0
chr1    10145   chr1:10145:A:AAC        AAC     A       .       .       RAF=0.00402537;AF=3.20157e-05;INFO=1    GT:DS:GP        0|0:0:1,0,0
chr1    10146   chr1:10146:A:AC AC      A       .       .       RAF=0.543669;AF=0.492588;INFO=1 GT:DS:GP        1|0:0.985:0.147,0.72,0.133
chr1    10146   chr1:10146:A:ACC        ACC     A       .       .       RAF=0.000365943;AF=0;INFO=1     GT:DS:GP        0|0:0:1,0,0
chr1    10146   chr1:10146:A:ACCCCT     ACCCCT  A       .       .       RAF=0.000243962;AF=1.55442e-05;INFO=1   GT:DS:GP        0|0:0:1,0,0
```

and these are the first few lines of my `pruning_sites`:

```
chr1:10146:A:AC
chr1:10180:C:T
chr1:10329:A:AC
chr1:10333:C:CT
chr1:10354:A:C
chr1:10390:C:CCCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA
chr1:10439:A:AC
chr1:10443:C:T
chr1:10492:C:T
chr1:10583:A:G
```

Surprisingly, if I remove `--set-all-var-ids @:#:\$1:\$2` from the plink2 command, I get no error, and this is strange since that syntax should indeed enforce lex order. Interestingly, plink2 creates a temporary file `-temporary.pvar` while running, which turns out to be a VCF where the `CHROM` field is, surprisingly, `1` instead of `chr1`. And indeed, if I try using `--set-all-var-ids chr@:#:\$1:\$2` I get no error.

It would be tempting to remove `--set-all-var-ids @:#:\$1:\$2` altogether, and assume that the variant IDs of all input files are already in the correct format. But I don't know if this holds at all points where this task is called in the entire codebase...

**Remark:** `set-all-var-ids` occurs with the same format also in `ScoringTasks.ScoreVcf`, `ScoringTasks.ExtractIDsPlink`, `CKDRiskAdjustment.GenotypeG1G2RiskAlleles`, `PerformPopulationPCA.SelectSitesOriginalArray`. Maybe we should check each one of these occurrences to make sure they work as intended?

**Comment by kachulis** [comment]
This can be fixed using the [--output-chr](https://www.cog-genomics.org/plink/2.0/data#irreg_output) option to control how plink encodes chromosomes in its temporary intermediate files.
