### ISSUE TITLE
Testing only wdls with modified dependencies

### ISSUE THREAD

**Issue by kachulis** [broadinstitute/palantir-workflows#184]
`womtools validate` has a `-l` option which will list all wdls which a particular wdl is dependent on.  I think we could combine this with https://github.com/marketplace/actions/changed-files, and a little simple python script to pretty easily have tests only run for which dependencies have changed.

**Comment by rickymagner** [comment]
@kachulis This was addressed/fixed by #186 right?

**Comment by kachulis** [comment]
yes, it was!
