### ISSUE TITLE
Example inputs for FindSamplesAndBenchmark have the wrong picard jar

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/palantir-workflows#77]
This jar https://github.com/broadinstitute/palantir-workflows/blob/main/BenchmarkVCFs/FindSamplesAndBenchmark_input.json#L10 

doesn't work as expected. We need a cloud friendly Picard jar, but apparently the latest version of picard gives an error: `Exception in thread "main" java.nio.file.ProviderNotFoundException: Provider "gs" not found`. We should track this down so that a released version of Picard can be used for fingerprinting in the FindSamlesAndBenchmark WDL.

**Comment by rickymagner** [comment]
This should be fixed in #86
