### ISSUE TITLE
Not specifying optional stratIntervals/stratLabels in FindSamplesAndBenchmark results in error.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/palantir-workflows#82]
Trying to do this on Terra gave me this error at the BenchmarkVCFs step: `Failed to evaluate input 'stratLabels' (reason 1 of 1): assertion failed: base member type WomMaybeEmptyArrayType(WomStringType) and womtype WomMaybeEmptyArrayType(WomSingleFileType) are not compatible`. Haven't looked too closely, but perhaps the following line is to blame? https://github.com/broadinstitute/palantir-workflows/blob/92b16f58f2a169f8982ef6a7f25a59cc99f6fdf8/BenchmarkVCFs/FindSamplesAndBenchmark.wdl#L109

There might also be some interaction between how the optional array types are specified at the FindSamplesAndBenchmark and BenchmarkVCFs levels, but I must admit I'm not up to date on best practices for optionals in WDL.

**Comment by meganshand** [comment]
Can you provide your inputs? Or were you using the inputs json here: https://github.com/broadinstitute/palantir-workflows/blob/main/BenchmarkVCFs/FindSamplesAndBenchmark_input.json ?

**Comment by samuelklee** [comment]
I think you should be able to see the job at https://job-manager.dsde-prod.broadinstitute.org/jobs/27ac8a1e-777d-4478-bc07-9e42d38197c4. Let me know if anyone else would like access.

**Comment by meganshand** [comment]
Ah thanks I see that the stratInterval + stratLabel are empty not optional, and now that I reread the title of this issue I understand :)

**Comment by michaelgatzen** [comment]
Can I get access to the workflow as well please?

**Comment by samuelklee** [comment]
@michaelgatzen you should have reader access to the workspace and I've made the workflow public (although I think it matches the current version in this repo).

**Comment by rickymagner** [comment]
This should be fixed in #86. If one uses the wdl from the main branch, it should work with this use case! Let us know if there are any other problems
